import { CityTimezone } from '../types';

export const ALL_CITIES: CityTimezone[] = [
  {
    id: 'lax',
    city: 'Los Angeles',
    country: 'United States',
    airportCode: 'LAX',
    airportName: 'Los Angeles International',
    timezone: 'America/Los_Angeles',
    lat: 33.9416,
    lon: -118.4085,
    flightNumber: 'AA 102',
    gate: 'T4-42',
  },
  {
    id: 'jfk',
    city: 'New York',
    country: 'United States',
    airportCode: 'JFK',
    airportName: 'John F. Kennedy International',
    timezone: 'America/New_York',
    lat: 40.6413,
    lon: -73.7781,
    flightNumber: 'DL 408',
    gate: 'T2-18',
  },
  {
    id: 'lhr',
    city: 'London',
    country: 'United Kingdom',
    airportCode: 'LHR',
    airportName: 'Heathrow Airport',
    timezone: 'Europe/London',
    lat: 51.4700,
    lon: -0.4543,
    flightNumber: 'BA 178',
    gate: 'T5-B3',
  },
  {
    id: 'dxb',
    city: 'Dubai',
    country: 'United Arab Emirates',
    airportCode: 'DXB',
    airportName: 'Dubai International',
    timezone: 'Asia/Dubai',
    lat: 25.2532,
    lon: 55.3657,
    flightNumber: 'EK 204',
    gate: 'T3-A12',
  },
  {
    id: 'hnd',
    city: 'Tokyo',
    country: 'Japan',
    airportCode: 'HND',
    airportName: 'Haneda Airport',
    timezone: 'Asia/Tokyo',
    lat: 35.5494,
    lon: 139.7798,
    flightNumber: 'JL 006',
    gate: 'T3-114',
  },
  {
    id: 'sfo',
    city: 'San Francisco',
    country: 'United States',
    airportCode: 'SFO',
    airportName: 'San Francisco International',
    timezone: 'America/Los_Angeles',
    lat: 37.6213,
    lon: -122.3790,
    flightNumber: 'UA 880',
    gate: 'G98',
  },
  // Cities for "San" searches
  {
    id: 'sju',
    city: 'San Juan',
    country: 'Puerto Rico',
    airportCode: 'SJU',
    airportName: 'Luis Muñoz Marín International',
    timezone: 'America/Puerto_Rico',
    lat: 18.4394,
    lon: -66.0018,
    flightNumber: 'B6 304',
    gate: 'C2',
  },
  {
    id: 'sal',
    city: 'San Salvador',
    country: 'El Salvador',
    airportCode: 'SAL',
    airportName: 'El Salvador International',
    timezone: 'America/El_Salvador',
    lat: 13.4409,
    lon: -89.0557,
    flightNumber: 'AV 520',
    gate: 'G6',
  },
  {
    id: 'scl',
    city: 'Santiago',
    country: 'Chile',
    airportCode: 'SCL',
    airportName: 'Arturo Merino Benítez International',
    timezone: 'America/Santiago',
    lat: -33.3930,
    lon: -70.7858,
    flightNumber: 'LA 500',
    gate: 'T2-24',
  },
  {
    id: 'san',
    city: 'San Diego',
    country: 'United States',
    airportCode: 'SAN',
    airportName: 'San Diego International',
    timezone: 'America/Los_Angeles',
    lat: 32.7338,
    lon: -117.1933,
    flightNumber: 'AS 682',
    gate: 'T2-38',
  },
  {
    id: 'sjc',
    city: 'San Jose',
    country: 'United States',
    airportCode: 'SJC',
    airportName: 'Norman Y. Mineta San Jose',
    timezone: 'America/Los_Angeles',
    lat: 37.3639,
    lon: -121.9289,
    flightNumber: 'WN 1420',
    gate: 'B18',
  },
  {
    id: 'sat',
    city: 'San Antonio',
    country: 'United States',
    airportCode: 'SAT',
    airportName: 'San Antonio International',
    timezone: 'America/Chicago',
    lat: 29.5337,
    lon: -98.4698,
    flightNumber: 'UA 1198',
    gate: 'A4',
  },
  // Major global hubs
  {
    id: 'cdg',
    city: 'Paris',
    country: 'France',
    airportCode: 'CDG',
    airportName: 'Charles de Gaulle Airport',
    timezone: 'Europe/Paris',
    lat: 49.0097,
    lon: 2.5479,
    flightNumber: 'AF 022',
    gate: '2E-K45',
  },
  {
    id: 'sin',
    city: 'Singapore',
    country: 'Singapore',
    airportCode: 'SIN',
    airportName: 'Singapore Changi Airport',
    timezone: 'Asia/Singapore',
    lat: 1.3644,
    lon: 103.9915,
    flightNumber: 'SQ 322',
    gate: 'T3-B2',
  },
  {
    id: 'hkg',
    city: 'Hong Kong',
    country: 'China',
    airportCode: 'HKG',
    airportName: 'Hong Kong International',
    timezone: 'Asia/Hong_Kong',
    lat: 22.3080,
    lon: 113.9185,
    flightNumber: 'CX 884',
    gate: 'T1-65',
  },
  {
    id: 'syd',
    city: 'Sydney',
    country: 'Australia',
    airportCode: 'SYD',
    airportName: 'Sydney Kingsford Smith',
    timezone: 'Australia/Sydney',
    lat: -33.9399,
    lon: 151.1753,
    flightNumber: 'QF 001',
    gate: 'T1-10',
  },
  {
    id: 'gru',
    city: 'São Paulo',
    country: 'Brazil',
    airportCode: 'GRU',
    airportName: 'São Paulo/Guarulhos International',
    timezone: 'America/Sao_Paulo',
    lat: -23.4356,
    lon: -46.4731,
    flightNumber: 'LA 8060',
    gate: 'T3-312',
  },
  {
    id: 'ber',
    city: 'Berlin',
    country: 'Germany',
    airportCode: 'BER',
    airportName: 'Berlin Brandenburg Airport',
    timezone: 'Europe/Berlin',
    lat: 52.3667,
    lon: 13.5033,
    flightNumber: 'LH 190',
    gate: 'A14',
  },
  {
    id: 'ams',
    city: 'Amsterdam',
    country: 'Netherlands',
    airportCode: 'AMS',
    airportName: 'Amsterdam Airport Schiphol',
    timezone: 'Europe/Amsterdam',
    lat: 52.3105,
    lon: 4.7683,
    flightNumber: 'KL 642',
    gate: 'E19',
  },
  {
    id: 'zrh',
    city: 'Zurich',
    country: 'Switzerland',
    airportCode: 'ZRH',
    airportName: 'Zurich Airport',
    timezone: 'Europe/Zurich',
    lat: 47.4582,
    lon: 8.5555,
    flightNumber: 'LX 040',
    gate: 'E46',
  },
  {
    id: 'fco',
    city: 'Rome',
    country: 'Italy',
    airportCode: 'FCO',
    airportName: 'Leonardo da Vinci–Fiumicino',
    timezone: 'Europe/Rome',
    lat: 41.8003,
    lon: 12.2389,
    flightNumber: 'AZ 608',
    gate: 'E31',
  },
  {
    id: 'mad',
    city: 'Madrid',
    country: 'Spain',
    airportCode: 'MAD',
    airportName: 'Adolfo Suárez Madrid–Barajas',
    timezone: 'Europe/Madrid',
    lat: 40.4839,
    lon: -3.5680,
    flightNumber: 'IB 6251',
    gate: 'T4S-52',
  },
  {
    id: 'icn',
    city: 'Seoul',
    country: 'South Korea',
    airportCode: 'ICN',
    airportName: 'Incheon International',
    timezone: 'Asia/Seoul',
    lat: 37.4602,
    lon: 126.4407,
    flightNumber: 'KE 081',
    gate: 'T2-252',
  },
  {
    id: 'bkk',
    city: 'Bangkok',
    country: 'Thailand',
    airportCode: 'BKK',
    airportName: 'Suvarnabhumi Airport',
    timezone: 'Asia/Bangkok',
    lat: 13.6900,
    lon: 100.7501,
    flightNumber: 'TG 910',
    gate: 'D4',
  },
  {
    id: 'bom',
    city: 'Mumbai',
    country: 'India',
    airportCode: 'BOM',
    airportName: 'Chhatrapati Shivaji Maharaj',
    timezone: 'Asia/Kolkata',
    lat: 19.0896,
    lon: 72.8656,
    flightNumber: 'AI 101',
    gate: 'T2-47',
  },
  {
    id: 'cai',
    city: 'Cairo',
    country: 'Egypt',
    airportCode: 'CAI',
    airportName: 'Cairo International',
    timezone: 'Africa/Cairo',
    lat: 30.1219,
    lon: 31.4056,
    flightNumber: 'MS 985',
    gate: 'T3-G7',
  },
  {
    id: 'cpt',
    city: 'Cape Town',
    country: 'South Africa',
    airportCode: 'CPT',
    airportName: 'Cape Town International',
    timezone: 'Africa/Johannesburg',
    lat: -33.9715,
    lon: 18.6021,
    flightNumber: 'SA 318',
    gate: 'A8',
  },
  {
    id: 'hnl',
    city: 'Honolulu',
    country: 'United States',
    airportCode: 'HNL',
    airportName: 'Daniel K. Inouye International',
    timezone: 'Pacific/Honolulu',
    lat: 21.3187,
    lon: -157.9225,
    flightNumber: 'HA 022',
    gate: 'T1-A2',
  },
  {
    id: 'ord',
    city: 'Chicago',
    country: 'United States',
    airportCode: 'ORD',
    airportName: "O'Hare International",
    timezone: 'America/Chicago',
    lat: 41.9742,
    lon: -87.9073,
    flightNumber: 'UA 604',
    gate: 'T1-C10',
  },
  {
    id: 'yyz',
    city: 'Toronto',
    country: 'Canada',
    airportCode: 'YYZ',
    airportName: 'Toronto Pearson International',
    timezone: 'America/Toronto',
    lat: 43.6777,
    lon: -79.6248,
    flightNumber: 'AC 033',
    gate: 'T1-164',
  },
  {
    id: 'yvr',
    city: 'Vancouver',
    country: 'Canada',
    airportCode: 'YVR',
    airportName: 'Vancouver International',
    timezone: 'America/Vancouver',
    lat: 49.1967,
    lon: -123.1815,
    flightNumber: 'AC 007',
    gate: 'D58',
  },
  {
    id: 'mex',
    city: 'Mexico City',
    country: 'Mexico',
    airportCode: 'MEX',
    airportName: 'Benito Juárez International',
    timezone: 'America/Mexico_City',
    lat: 19.4361,
    lon: -99.0719,
    flightNumber: 'AM 404',
    gate: 'T2-56',
  },
  {
    id: 'eze',
    city: 'Buenos Aires',
    country: 'Argentina',
    airportCode: 'EZE',
    airportName: 'Ministro Pistarini International',
    timezone: 'America/Argentina/Buenos_Aires',
    lat: -34.8222,
    lon: -58.5358,
    flightNumber: 'AR 1302',
    gate: 'T-A3',
  },
  {
    id: 'kef',
    city: 'Reykjavik',
    country: 'Iceland',
    airportCode: 'KEF',
    airportName: 'Keflavík International',
    timezone: 'Atlantic/Reykjavik',
    lat: 63.9850,
    lon: -22.6056,
    flightNumber: 'FI 614',
    gate: 'D14',
  },
  {
    id: 'doh',
    city: 'Doha',
    country: 'Qatar',
    airportCode: 'DOH',
    airportName: 'Hamad International',
    timezone: 'Asia/Qatar',
    lat: 25.2731,
    lon: 51.6081,
    flightNumber: 'QR 701',
    gate: 'C20',
  },
  {
    id: 'ist',
    city: 'Istanbul',
    country: 'Turkey',
    airportCode: 'IST',
    airportName: 'Istanbul Airport',
    timezone: 'Europe/Istanbul',
    lat: 41.2753,
    lon: 28.7519,
    flightNumber: 'TK 001',
    gate: 'F12',
  },
  {
    id: 'akl',
    city: 'Auckland',
    country: 'New Zealand',
    airportCode: 'AKL',
    airportName: 'Auckland Airport',
    timezone: 'Pacific/Auckland',
    lat: -37.0082,
    lon: 174.7850,
    flightNumber: 'NZ 002',
    gate: 'Gate 8',
  },
  {
    id: 'mel',
    city: 'Melbourne',
    country: 'Australia',
    airportCode: 'MEL',
    airportName: 'Melbourne Airport',
    timezone: 'Australia/Melbourne',
    lat: -37.6690,
    lon: 144.8410,
    flightNumber: 'VA 820',
    gate: 'T3-12',
  },
  {
    id: 'nbo',
    city: 'Nairobi',
    country: 'Kenya',
    airportCode: 'NBO',
    airportName: 'Jomo Kenyatta International',
    timezone: 'Africa/Nairobi',
    lat: -1.3192,
    lon: 36.9278,
    flightNumber: 'KQ 100',
    gate: '1A',
  },
  {
    id: 'sea',
    city: 'Seattle',
    country: 'United States',
    airportCode: 'SEA',
    airportName: 'Seattle-Tacoma International',
    timezone: 'America/Los_Angeles',
    lat: 47.4502,
    lon: -122.3088,
    flightNumber: 'DL 240',
    gate: 'A6',
  },
  {
    id: 'den',
    city: 'Denver',
    country: 'United States',
    airportCode: 'DEN',
    airportName: 'Denver International',
    timezone: 'America/Denver',
    lat: 39.8561,
    lon: -104.6737,
    flightNumber: 'WN 450',
    gate: 'C34',
  },
  {
    id: 'mia',
    city: 'Miami',
    country: 'United States',
    airportCode: 'MIA',
    airportName: 'Miami International',
    timezone: 'America/New_York',
    lat: 25.7959,
    lon: -80.2870,
    flightNumber: 'AA 918',
    gate: 'D24',
  },
  {
    id: 'dub',
    city: 'Dublin',
    country: 'Ireland',
    airportCode: 'DUB',
    airportName: 'Dublin Airport',
    timezone: 'Europe/Dublin',
    lat: 53.4264,
    lon: -6.2499,
    flightNumber: 'EI 104',
    gate: 'T2-401',
  },
];

export const DEFAULT_CITY_IDS = ['lax', 'jfk', 'lhr', 'dxb', 'hnd', 'sfo'];

// Helper to get time info for a timezone
export function getTimeInfo(timezone: string, is24Hour = true) {
  const now = new Date();
  try {
    const formatter = new Intl.DateTimeFormat('en-US', {
      timeZone: timezone,
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: !is24Hour,
    });
    const parts = formatter.formatToParts(now);
    let hours = '00';
    let minutes = '00';
    let seconds = '00';
    let dayPeriod = '';

    for (const p of parts) {
      if (p.type === 'hour') hours = p.value;
      if (p.type === 'minute') minutes = p.value;
      if (p.type === 'second') seconds = p.value;
      if (p.type === 'dayPeriod') dayPeriod = p.value.toUpperCase();
    }

    // Offset in hours relative to UTC
    const dateInTz = new Date(now.toLocaleString('en-US', { timeZone: timezone }));
    const dateInUtc = new Date(now.toLocaleString('en-US', { timeZone: 'UTC' }));
    const offsetHours = Math.round((dateInTz.getTime() - dateInUtc.getTime()) / (1000 * 60 * 60));

    // Day of week & date
    const dateFormatted = new Intl.DateTimeFormat('en-US', {
      timeZone: timezone,
      weekday: 'short',
      month: 'short',
      day: '2-digit',
    }).format(now);

    // Is daytime (roughly 06:00 to 18:30)
    const rawHour = parseInt(new Intl.DateTimeFormat('en-US', {
      timeZone: timezone,
      hour: 'numeric',
      hour12: false,
    }).format(now), 10);
    const isDay = rawHour >= 6 && rawHour < 19;

    return {
      timeString: `${hours}:${minutes}`,
      secondsString: seconds,
      dayPeriod,
      offsetHours,
      dateFormatted,
      isDay,
      rawHour,
    };
  } catch {
    return {
      timeString: '12:00',
      secondsString: '00',
      dayPeriod: '',
      offsetHours: 0,
      dateFormatted: 'Sun, Oct 04',
      isDay: true,
      rawHour: 12,
    };
  }
}

// Compute difference relative to a reference city (home)
export function getTimeDifference(targetTimezone: string, homeTimezone: string): string {
  try {
    const now = new Date();
    const dateInTarget = new Date(now.toLocaleString('en-US', { timeZone: targetTimezone }));
    const dateInHome = new Date(now.toLocaleString('en-US', { timeZone: homeTimezone }));
    const diffHours = Math.round((dateInTarget.getTime() - dateInHome.getTime()) / (1000 * 60 * 60));

    if (diffHours === 0) return 'HOME';
    if (diffHours > 0) return `+${diffHours}H`;
    return `${diffHours}H`;
  } catch {
    return '0H';
  }
}
